<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>GUI_517OF</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\BE_517OF\BE_517OF.csproj" />
		<ProjectReference Include="..\BLL_517OF\BLL_517OF.csproj" />
		<ProjectReference Include="..\SEGURIDAD_517OF\SEGURIDAD_517OF.csproj" />
	</ItemGroup>
</Project>